### ISSUE TITLE
How to change the log level (I want to see only INFO logs without any DEBUG logs)?

### ISSUE THREAD

**Issue by Shrikantbehera** [cloudfoundry/uaa#1304]
**### What version of UAA are you running?**
4.14.0

 

**### How are you deploying the UAA?**
I am deploying the UAA
- as part of a commercial Cloud Foundry distribution

 

**### What did you do?**

 

I tried to set logging level property in uaa.yml file
```
uaa:
  logging_level:
    description: Set UAA logging level.  (e.g. TRACE, DEBUG, INFO)
    default: INFO
```
**### What did you expect to see? What goal are you trying to achieve with the UAA?**

 

I want the see only INFO logs

 

**### What did you see instead?**
[uaa-logs.txt](https://github.com/cloudfoundry/uaa/files/4669143/uaa-logs.txt)
