### ISSUE TITLE
Request: Make SAML configuration optional

### ISSUE THREAD

**Issue by acosta11** [cloudfoundry/uaa#1346]
Hello UAA friends,

My pair and I from the Release Integration team are cleaning up our UAA config for the default minimal installation included in [cf-for-k8s](https://github.com/cloudfoundry/cf-for-k8s) and ran into an issue trying to remove the certificate used for SAML, which we don't think is required for a minimal standalone UAA. Note that we suspect falling back to the defaults provided by UAA is sufficient for our immediate goal of cleaning up the cf-for-k8s user interface, so we don't feel a strong sense of urgency on the request. We just wanted to let you all know in case this behavior is something you would want to change. Also mentioned in the CloudFoundry Slack channel [here](https://cloudfoundry.slack.com/archives/C03FXANBV/p1594243428220700).

### What version of UAA are you running?
v74.22.0

What output do you see from `curl <YOUR_UAA>/info -H'Accept: application/json'`
N.A. The UAA app container does not start up successfully

### How are you deploying the UAA?
I am deploying the UAA in cf-for-k8s with the provided k8s templates.

### What did you do?
1. Generate values for cf-for-k8s as specified in [its deploy guide].(https://github.com/cloudfoundry/cf-for-k8s/blob/master/docs/deploy.md).
2. Manually use empty values for the service_provider configuration values.
```
login:
  service_provider:
    key: ""
    key_password: ""
    certificate: ""
```
3. Map those values into the UAA ConfigMap (which matches the BOSH job spec)
```
login:
  url: #@ "https://login." + <system_domain>
  entityBaseURL: #@ "https://uaa." + <system_domain>
  entityID: cloudfoundry-saml-login
  serviceProviderKey: ""
  serviceProviderKeyPassword: ""
  serviceProviderCertificate: ""
```
4. Run the UAA image with the above configuration mounted as part of cf-for-k8s following the deploy guide linked 1.

### What did you expect to see? What goal are you trying to achieve with the UAA?
UAA started up successfully. We would like to stand up a minimal UAA for use with a fresh Cloud Foundry running on Kubernetes to validate integration and basic workflows.

### What did you see instead?
UAA failed to start up with a bean initialization error:
```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'idpInitiatedLoginController'
```

Thanks,
Andrew and @cloudfoundry/cf-release-integration
