### ISSUE TITLE
Unable to load login page getting home controller Internal error

### ISSUE THREAD

**Issue by pallav-bh** [cloudfoundry/uaa#1788]
**SECURITY NOTICE: If you have found a security problem in the UAA, please do not file a public github issue. Instead, please send an email to security@cloudfoundry.org**

Thanks for taking the time to file an issue. You'll minimize back and forth and help us help you more effectively by answering all of the following questions as specifically and completely as you can.

### What version of UAA are you running?
75.14

What output do you see from `curl <YOUR_UAA>/info -H'Accept: application/json'`?
Not able to reach the application getting redirected to /login

### How are you deploying the UAA?

I am deploying the UAA using ytt into a kubernetes cluster. This is happening only when we are assigning a subdomain to reach UAA. Issue not happening in local.

### What did you do?DefaultRedirectStrategy
Deployed UAA to a kubernetes cluster in cloud.
Assigned a subdomain for UAA and added a ingress to reach the service.
Made changes to the configuration accordingly and example of the config given below:
  

If possible, provide a recipe for reproducing the error. Exact `curl` or `uaac` commands with verbose output are helpful. If your problem is configuration-related, please include portions of your uaa.yml or bosh deployment manifest that you believe may be relevant (but do not divulge secrets!)

 ```
issuer:
      uri: https://forms-dev.company.systems/auaa
uaa:
      zones:
        internal:
          hostnames:
            - forms-dev.company.systems 
      url: https://forms-dev.company.systems/auaa
      token:
        url: https://forms-dev.company.systems/auaa/oauth/token
      approvals:
        url: https://forms-dev.company.systems/auaa/approvals
      login:
        url: https://forms-dev.company.systems/auaa/authenticate
    LOGIN_SECRET: avitas_awa_app_dev
login:
      url: https://forms-dev.company.systems/auaa
      homeRedirect: https://forms-dev.company.systems/

```

## portion of the ingress for reference
```
spec:
  tls:
    - hosts:
        - forms-dev.company.systems
      secretName: demo-tls-cert
  rules:
    - host: forms-dev.company.systems
      http:
        paths:
          - path: /auaa(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              serviceName: uaa
              servicePort: 8080
```

### What did you expect to see? What goal are you trying to achieve with the UAA?
Expected to atleast see the login screen on the 1st load and not get redirected.
Just wanted to deploy a bareminimum UAA deployment
[logs-from-uaa-in-uaa-776f9b4b8c-jz8bc (2).txt](https://github.com/cloudfoundry/uaa/files/7985928/logs-from-uaa-in-uaa-776f9b4b8c-jz8bc.2.txt)

### What did you see instead?
The login page doesnt load instead throws an error and redirects to /login.
i.e    https://forms-dev.company.systems/login 

Please include UAA logs if available.
