### ISSUE TITLE
External group mapping to JWT scopes (SAML) does not work as expected

### ISSUE THREAD

**Issue by pdambrauskas** [cloudfoundry/uaa#1790]
Hello, I have uaa group mapping configured as follows:
```yaml
scim:
            groups:
                group1: Group1
                group2: Group2
            external_groups:
                saml:
                    external_id1:
                        - group1
                    external_id2:
                        - group2
```

Also I've added external groups to `externalGroupsWhitelist` on my SAML provider.
When trying to log in, I can see `White listed external SAML groups:'[external_id1, external_id2]'` logged.
So I came to the conclusion that groups are mapped correctly (https://github.com/cloudfoundry/uaa/blob/develop/server/src/main/java/org/cloudfoundry/identity/uaa/provider/saml/LoginSamlAuthenticationProvider.java#L168)

But when I inspect JWT token, I can see no external group scopes (internal groups are visible in the scope list).

I checked UAA code, responsible for user scope generation:
https://github.com/cloudfoundry/uaa/blob/ad4a24861853348b52627c03541bd8b50d655e51/server/src/main/java/org/cloudfoundry/identity/uaa/oauth/UaaAuthorizationRequestManager.java#L369

Which, gets internal groups from database:
https://github.com/cloudfoundry/uaa/blob/ad4a24861853348b52627c03541bd8b50d655e51/server/src/main/java/org/cloudfoundry/identity/uaa/user/JdbcUaaUserDatabase.java#L204

But does nothing about the external groups. Is this expected behavior? 
As I understand, it would work In a different way, if user database bean was missing https://github.com/cloudfoundry/uaa/blob/ad4a24861853348b52627c03541bd8b50d655e51/server/src/main/java/org/cloudfoundry/identity/uaa/oauth/UaaAuthorizationRequestManager.java#L373-L375

In that case authorities would be retrieved from Security context, where external groups are present. Should I disable user database bean?
