### ISSUE TITLE
Q: Multiple searchBase paths possible?

### ISSUE THREAD

**Issue by N00ree** [cloudfoundry/uaa#1897]
Hi,

Is it possible to work with multiple `searchBase `paths in the group search filter section?

Currently I have a LDAP configuration like this:
```yaml
ldap:
  profile:
    file: ldap/ldap-search-and-bind.xml
  base:
    url: "ldaps://ldap-test:636"
    userDn: "cn=admin,dc=example,dc=org"
    password: "{{ ldap_password }}"
    searchBase: "dc=example,dc=org"
    searchFilter: "(&(objectclass=posixAccount)(cn={0}))"
  ssl:
    skipverification: true
    tls: none
  groups:
    file: ldap/ldap-groups-map-to-scopes.xml
    searchBase: "ou=groups,dc=example,dc=org"
    searchSubtree: true
    groupSearchFilter: "(&(objectClass=posixGroup)(memberUid={0}))"
    maxSearchDepth: 15
```

I want to use multiple searchBase paths like this:
```yaml
searchBase:
  -  "ou=groups,dc=example,dc=org"
  -  "ou=groups2,dc=example,dc=org"
```

Is this possible?

regards
