### ISSUE TITLE
UAA cannot start with multiple secrets in cf client

### ISSUE THREAD

**Issue by strehle** [cloudfoundry/uaa#2100]
### What version of UAA are you running?

76.3.0, but with develop same issue

### How are you deploying the UAA?

- using a bosh release I downloaded from bosh.io
- using cf-deployment

### What did you do?

setup  in cf the well known empty secret but do this after the cf client has multiple secrets already.

### What did you expect to see? What goal are you trying to achieve with the UAA?

UAA cannot start because of stack

Caused by: java.lang.IllegalArgumentException: rawPassword cannot be null
at org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder.matches(BCryptPasswordEncoder.java:123) ~[spring-security-crypto-5.7.4.jar:5.7.4]
at org.cloudfoundry.identity.uaa.util.beans.BackwardsCompatibleDelegatingPasswordEncoder.matches(BackwardsCompatibleDelegatingPasswordEncoder.java:30) ~[cloudfoundry-identity-server-76.3.0.jar:?]
at org.cloudfoundry.identity.uaa.client.ClientAdminBootstrap.updatePasswordsIfChanged(ClientAdminBootstrap.java:275) ~[cloudfoundry-identity-server-76.3.0.jar:?]
at org.cloudfoundry.identity.uaa.client.ClientAdminBootstrap.addNewClients(ClientAdminBootstrap.java:221) ~[cloudfoundry-identity-server-76.3.0.jar:?]
at org.cloudfoundry.identity.uaa.client.ClientAdminBootstrap.afterPropertiesSet(ClientAdminBootstrap.java:100) ~[cloudfoundry-identity-server-76.3.0.jar:?]

### What did you see instead?

Please include UAA logs if available.

**Comment by strehle** [comment]
Info for reproducing the issue

Add this section in your uaa.yml

```
oauth:
  clients:
    cf:
      access-token-validity: 600
      authorities: uaa.none
      authorized-grant-types: password,refresh_token
      override: true
      refresh-token-validity: 2592000
      scope: openid
      secret:
        - ''
        -
```

then you see see in uaa.log


Caused by: java.lang.IllegalArgumentException: rawPassword cannot be null
        at org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder.matches(BCryptPasswordEncoder.java:123) ~[spring-security-crypto-5.7.4.jar:5.7.4]
        at org.cloudfoundry.identity.uaa.util.beans.BackwardsCompatibleDelegatingPasswordEncoder.matches(BackwardsCompatibleDelegatingPasswordEncoder.java:30) ~[cloudfoundry-identity-server-0.0.0.jar:?]
        at org.cloudfoundry.identity.uaa.client.ClientAdminBootstrap.updatePasswordsIfChanged(ClientAdminBootstrap.java:275) ~[cloudfoundry-identity-server-0.0.0.jar:?]
