### ISSUE TITLE
Support Azure AD with OIDC Proxy using private_key_jwt authentication

### ISSUE THREAD

**Issue by strehle** [cloudfoundry/uaa#2109]
Initial isssue https://github.com/cloudfoundry/uaa/issues/1933. During https://github.com/cloudfoundry/uaa/pull/2106 found problem with interop towards Azure AD

Azure relys on this claim, e.g. 
https://learn.microsoft.com/en-us/azure/active-directory/develop/active-directory-certificate-credentials
UAA uses raw keys not X509 for JWT RS256, and therefore a x5c , x5t etc cannot be calculated on a real key.

### What version of UAA are you running?

develop

### How are you deploying the UAA?

I am deploying the UAA

- locally only using gradlew
- as part of a commercial Cloud Foundry distribution

### What did you do?

Setup OIDC provxy to Azure AD

### What did you expect to see? What goal are you trying to achieve with the UAA?

Successfull OIDC proxy authentication through Azure AD towards UAA

### What did you see instead?

Please include UAA logs if available.

Exception from Azure
There was an error when authenticating against the external identity provider: 400 Bad Request: "{"error":"invalid_request","error_description":"AADSTS5002726: Invalid JWT token. Found unsupported token header. Supported headers are: 'alg','typ','x5t','x5c','kid','use','enc','ctx','nonce','rh','kdf_ver'\r\nTrace ID: 953b0bd4-3a8f-4e9a-8fd5-b941c7c35f00\r\nCorrelation ID: 6aec6815-90f0-49ea-8e37-19daa41e4d21\r\nTimestamp: 2023-03-29 12:53:10Z","error_codes":[5002726],"timestamp":"2023-03-29 12:53:10Z","trace_id":"953b0bd4-3a8f-4e9a-8fd5-b941c7c35f00","correlation_id":"6aec6815-90f0-49ea-8e37-19daa41e4d21"}"

**Comment by strehle** [comment]
Steps to reproduce:

1. configure OIDC proxy in UAA , use your AAD application
Example yaml config in uaa.yml
```
login:
  oauth:
    providers:
      azure.proxy:
        type: oidc1.0
        passwordGrantEnabled: true
        discoveryUrl: https://login.microsoftonline.com/<your-AAD-tenant-id>/v2.0/.well-known/openid-configuration
        issuer: https://login.microsoftonline.com/<your-AAD-tenant-id>/v2.0
        scopes:
          - openid
          - email
          - profile
          - offline_access
        linkText: Login with Azure Proxy
        relyingPartyId: <your-AAD-application-client-id>
        groupMappingMode: AS_SCOPES
        jwtclientAuthentication: true
        attributeMappings:
          family_name: last_name
          given_name: first_name
          email: email
          user_name: email
          external_groups:
            roles
        showLinkText: true
```
2. Register the certificate of your JWT singing key into Credential Configuration in your App registrations, Section: Certificates & secrets, subsection. Certificate, e.g. https://learn.microsoft.com/en-us/azure/active-directory/develop/active-directory-certificate-credentials 
3. Login and then you see the exception 

2 Issues 
a) jku header is not allowed and from OIDC standard that makes sense because private_key_jwt in context of OIDC should not use OAuth stuff like jku
b) x5t header cannot be created within UAA. A solution would be that UAA allows to configure a X509 certificate as singing-cert because with that a x5t could be calculated.
