### ISSUE TITLE
UAA token exchange with AzureAD

### ISSUE THREAD

**Issue by pat-git023** [cloudfoundry/uaa#2493]
Hello,

I would like to a RFC 8963 OAuth 2.0 Token Exchange but I can not find any dokumentation so far.
Is this supported bei UAA at all?
If yes could someone please point me to the part in the documentation or is there a sample where I can see how to configure that.

I have an AzureAD access token of a user and I would like to exchange that with an internal UAA token with the corresponding scopes.

### What version of UAA are you running?
uaa-76.20.0

What output do you see from `curl <YOUR_UAA>/info -H'Accept: application/json'`?
```json
{
    "app": {
        "version": "0.0.0"
    },
    "showLoginLinks": true,
    "links": {
        "uaa": "http://localhost:8080/uaa",
        "login": "http://localhost:8080/uaa"
    },
    "zone_name": "uaa",
    "entityID": "cloudfoundry-saml-login",
    "commit_id": "be5c5b4",
    "idpDefinitions": {},
    "prompts": {
        "username": [
            "text",
            "User"
        ],
        "password": [
            "password",
            "Password"
        ],
        "passcode": [
            "password",
            "Temporary Authentication Code ( Get one at http://localhost:8080/uaa/passcode )"
        ]
    },
    "timestamp": "2023-09-06T22:37:51+0200"
}
```

### How are you deploying the UAA?

I am deploying the UAA

- locally only using gradlew

Thank you very much for your help!

Best regards
Patrick

**Comment by strehle** [comment]
UAA does not support the standard RFC 8963 OAuth 2.0 Token Exchange -> urn:ietf:params:oauth:grant-type:token-exchange, but only JWT Bearer -> urn:ietf:params:oauth:grant-type:jwt-bearer.  (the urn strings are the grant types)

The exchange from an ID Token from Azure to UAA Token would work with Azure AD using JWT bearer, but you need to register Azure as IDP of Type OIDC. e.g. https://docs.cloudfoundry.org/api/uaa/version/76.21.0/index.html#oauth-oidc

here is the API doc for jwt bearer https://docs.cloudfoundry.org/api/uaa/version/76.21.0/index.html#jwt-bearer-token-grant

**Comment by pat-git023** [comment]
Thank you for your quick response!!!

I did try out the jwt-bearer flow however I still have some problems where I have no idea how to fix it. 
My identity providers in uaa.yml are:
```yaml
login:
  oauth:
    providers:
      azure:
        type: oidc1.0
        authUrl: https://login.microsoftonline.com/138a4c3b-131c-4465-8863-f3f8aba8966f/oauth2/v2.0/authorize
        tokenUrl: https://login.microsoftonline.com/138a4c3b-131c-4465-8863-f3f8aba8966f/oauth2/v2.0/token
        issuer: https://login.microsoftonline.com/138a4c3b-131c-4465-8863-f3f8aba8966f/v2.0
        discoveryUrl: https://login.microsoftonline.com/138a4c3b-131c-4465-8863-f3f8aba8966f/v2.0/.well-known/openid-configuration
        scopes:
          - openid
          - email
          - profile
        linkText: Azure AD
        showLinkText: true
        addShadowUserOnLogin: true
        relyingPartyId: 9c730816...
        relyingPartySecret: <myAzureClientSecret>
        storeCustomAttributes: true
        attributeMappings:
          given_name: given_name
          family_name: family_name
          user_name: email
          user.attribute.picture : picture
      azure2:
        type: oidc1.0
        authUrl: https://sts.windows.net/138a4c3b-131c-4465-8863-f3f8aba8966f/oauth2/v2.0/authorize
        tokenUrl: https://sts.windows.net/138a4c3b-131c-4465-8863-f3f8aba8966f/oauth2/v2.0/token
        issuer: https://sts.windows.net/138a4c3b-131c-4465-8863-f3f8aba8966f/
        userInfoUrl: https://graph.microsoft.com/v1.0/users
        discoveryUrl: https://sts.windows.net/138a4c3b-131c-4465-8863-f3f8aba8966f/v2.0/.well-known/openid-configuration
        scopes:
          - openid
          - email
          - profile
        linkText: Azure2 AD
        showLinkText: true
        addShadowUserOnLogin: true
        relyingPartyId: 9c730816...
        relyingPartySecret: <myAzureClientSecret>
        storeCustomAttributes: true
        attributeMappings:
          email: upn
          given_name: given_name
          family_name: family_name
          user_name: name
          user.attribute.picture: picture
```

If I try to execute the jwt-bearer flow e.g. in Postman or with curl (command line see below) I always get an `invalid_token` error with the description `Could not verify token signature.`
After that I had a look at the log and there I could the the following exception:
```bash
2023-09-20 11:11:21 09:11:21.214 [http-nio-8080-exec-2] ERROR org.cloudfoundry.identity.uaa.util.JwtTokenSignedByThisUAA - Invalid token (could not verify signature)
2023-09-20 11:11:21 org.springframework.security.jwt.crypto.sign.InvalidSignatureException: RSA Signature did not match content
2023-09-20 11:11:21     at org.springframework.security.jwt.crypto.sign.RsaVerifier.verify(RsaVerifier.java:59) ~[spring-security-jwt-1.1.1.RELEASE.jar:?]
2023-09-20 11:11:21     at org.cloudfoundry.identity.uaa.oauth.jwt.CommonSignatureVerifier.verify(CommonSignatureVerifier.java:62) ~[cloudfoundry-identity-server-0.0.0.jar:?]
2023-09-20 11:11:21     at org.cloudfoundry.identity.uaa.oauth.jwt.ChainedSignatureVerifier.verify(ChainedSignatureVerifier.java:49) ~[cloudfoundry-identity-server-0.0.0.jar:?]
2023-09-20 11:11:21     at org.cloudfoundry.identity.uaa.oauth.jwt.JwtImpl.verifySignature(JwtHelper.java:182) ~[cloudfoundry-identity-server-0.0.0.jar:?]
2023-09-20 11:11:21     at org.cloudfoundry.identity.uaa.util.JwtTokenSignedByThisUAA.checkSignature(JwtTokenSignedByThisUAA.java:131) ~[cloudfoundry-identity-server-0.0.0.jar:?]
```

I am wondering why does this excepation is thrown by the `JwtTokenSignedByThisUAA` class? 
Since I am providing an Azure token this can not be signed by this UAA instance, right?

Any idea what I am still doing wrong?

Here is my curl command line:
```bash
curl 'http://localhost:8080/oauth/token' -i -X POST \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'client_id=azure-token-exchange-client&client_secret=top-secret&grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ajwt-bearer&token_format=opaque&response_type=token+id_token&assertion=eyJ0eXAiOiJKV1QiLCJub25jZSI6IllzZkx5b3hEcHVZME5mb2Y1LWRxUnlOZTl5QWt6aThqMkppYXZuXzkwR1EiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8xMzhhNGMzYi0xMzFjLTQ0NjUtODg2My1mM2Y4YWJhODk2NmYvIiwiaWF0IjoxNjk1MjAwNTY1LCJuYmYiOjE2OTUyMDA1NjUsImV4cCI6MTY5NTIwNTQzNiwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IkFWUUFxLzhVQUFBQVJORzJYZXAya2NJNzJFbE5ZbWhuZXlVM1N0eFJDZ2VTOTlsdlJDSm9scmdISHhEZUtnbm9vSU8rSDltdzJjMnVqNTFtRENGUU1aMnNZK3dzQ3lmbytOanZCaUs5R1k4MGpVNWgyczQ1U2VRPSIsImFtciI6WyJwd2QiLCJtZmEiXSwiYXBwX2Rpc3BsYXluYW1lIjoiQmFzaWNSZWFjdFRhYi1hYWQiLCJhcHBpZCI6IjcxNWFkZTlkLTc3YmUtNGMyNS1hZTFlLTA0ZWExZGE0ZjZmMSIsImFwcGlkYWNyIjoiMCIsImZhbWlseV9uYW1lIjoiR2VsbCIsImdpdmVuX25hbWUiOiJQYXRyaWNrIiwiaWR0eXAiOiJ1c2VyIiwiaXBhZGRyIjoiMjE3LjkzLjIyOC4yMTEiLCJuYW1lIjoiUGF0cmljayBHZWxsIiwib2lkIjoiYjc2OThjZDEtYjBiYi00ZTA2LWJkN2ItNTcwMDJmZGFlZTQ1IiwicGxhdGYiOiI1IiwicHVpZCI6IjEwMDMyMDAyQ0JFMzVCNjMiLCJyaCI6IjAuQWE4QU8weUtFeHdUWlVTSVlfUDRxNmlXYndNQUFBQUFBQUFBd0FBQUFBQUFBQUN2QUxJLiIsInNjcCI6Im9wZW5pZCBQcmVzZW5jZS5SZWFkIHByb2ZpbGUgVXNlci5SZWFkIGVtYWlsIiwic2lnbmluX3N0YXRlIjpbImttc2kiXSwic3ViIjoibnNvbkZ3bWVReHNvVTh0S1lqLVdoS2pVbmJTdV9sNFVULURsbHRwTm1iSSIsInRlbmFudF9yZWdpb25fc2NvcGUiOiJFVSIsInRpZCI6IjEzOGE0YzNiLTEzMWMtNDQ2NS04ODYzLWYzZjhhYmE4OTY2ZiIsInVuaXF1ZV9uYW1lIjoicGF0cmlja0AyZ2hobWIub25taWNyb3NvZnQuY29tIiwidXBuIjoicGF0cmlja0AyZ2hobWIub25taWNyb3NvZnQuY29tIiwidXRpIjoiVUJTVExqXzFFVTZKc1lJMzhud2tBQSIsInZlciI6IjEuMCIsIndpZHMiOlsiNjJlOTAzOTQtNjlmNS00MjM3LTkxOTAtMDEyMTc3MTQ1ZTEwIiwiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il0sInhtc19zdCI6eyJzdWIiOiJpQTFqcHJNaVR2LTJpd0QtN25ZVlZjTGJfR1Jrd0VLQlJraWtHTWZfYlRvIn0sInhtc190Y2R0IjoxNjkwNDYyMjc4LCJ4bXNfdGRiciI6IkVVIn0.axO_qo7fOSfdh9anwP1Hg5wvTuN8-_RDgevq30hvWZCXbKEidlKVCbq6QIZZlDss-gNl1y3ZNZhoXYgDM6hnWH2nr7kmvHTH830DNdkIkOg_i9vWKKqLINg8hUmuWZ4-MnMY--d3u0tAJd4ngWR1MwDlhhazGGodSv-GOUbLw2703LxcitN87h-rpL-5sI-0U_NTaTATskV_QqyJtVAFO2RQY32_w_-EkUMwhppTcDtAnRtZTTuRWR9C3SDZi4rWo3-Mov8v37rwzI7_UO4meowstcMiaSAGewfkNw0U__q9kmGkwLNngXuyZ0hSoBDFGBKmqB3ilYlUqn3D6n4rSQ'
```

Here is a bit mor readable version:
```bash
curl --location 'http://localhost:8080/oauth/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'client_id=azure-token-exchange-client' \
--data-urlencode 'client_secret=top-secret' \
--data-urlencode 'grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer' \
--data-urlencode 'token_format=opaque' \
--data-urlencode 'response_type=token+id_token' \
--data-urlencode 'assertion=eyJ0eXAiOiJKV1QiLCJub25jZSI6IllzZkx5b3hEcHVZME5mb2Y1LWRxUnlOZTl5QWt6aThqMkppYXZuXzkwR1EiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8xMzhhNGMzYi0xMzFjLTQ0NjUtODg2My1mM2Y4YWJhODk2NmYvIiwiaWF0IjoxNjk1MjAwNTY1LCJuYmYiOjE2OTUyMDA1NjUsImV4cCI6MTY5NTIwNTQzNiwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IkFWUUFxLzhVQUFBQVJORzJYZXAya2NJNzJFbE5ZbWhuZXlVM1N0eFJDZ2VTOTlsdlJDSm9scmdISHhEZUtnbm9vSU8rSDltdzJjMnVqNTFtRENGUU1aMnNZK3dzQ3lmbytOanZCaUs5R1k4MGpVNWgyczQ1U2VRPSIsImFtciI6WyJwd2QiLCJtZmEiXSwiYXBwX2Rpc3BsYXluYW1lIjoiQmFzaWNSZWFjdFRhYi1hYWQiLCJhcHBpZCI6IjcxNWFkZTlkLTc3YmUtNGMyNS1hZTFlLTA0ZWExZGE0ZjZmMSIsImFwcGlkYWNyIjoiMCIsImZhbWlseV9uYW1lIjoiR2VsbCIsImdpdmVuX25hbWUiOiJQYXRyaWNrIiwiaWR0eXAiOiJ1c2VyIiwiaXBhZGRyIjoiMjE3LjkzLjIyOC4yMTEiLCJuYW1lIjoiUGF0cmljayBHZWxsIiwib2lkIjoiYjc2OThjZDEtYjBiYi00ZTA2LWJkN2ItNTcwMDJmZGFlZTQ1IiwicGxhdGYiOiI1IiwicHVpZCI6IjEwMDMyMDAyQ0JFMzVCNjMiLCJyaCI6IjAuQWE4QU8weUtFeHdUWlVTSVlfUDRxNmlXYndNQUFBQUFBQUFBd0FBQUFBQUFBQUN2QUxJLiIsInNjcCI6Im9wZW5pZCBQcmVzZW5jZS5SZWFkIHByb2ZpbGUgVXNlci5SZWFkIGVtYWlsIiwic2lnbmluX3N0YXRlIjpbImttc2kiXSwic3ViIjoibnNvbkZ3bWVReHNvVTh0S1lqLVdoS2pVbmJTdV9sNFVULURsbHRwTm1iSSIsInRlbmFudF9yZWdpb25fc2NvcGUiOiJFVSIsInRpZCI6IjEzOGE0YzNiLTEzMWMtNDQ2NS04ODYzLWYzZjhhYmE4OTY2ZiIsInVuaXF1ZV9uYW1lIjoicGF0cmlja0AyZ2hobWIub25taWNyb3NvZnQuY29tIiwidXBuIjoicGF0cmlja0AyZ2hobWIub25taWNyb3NvZnQuY29tIiwidXRpIjoiVUJTVExqXzFFVTZKc1lJMzhud2tBQSIsInZlciI6IjEuMCIsIndpZHMiOlsiNjJlOTAzOTQtNjlmNS00MjM3LTkxOTAtMDEyMTc3MTQ1ZTEwIiwiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il0sInhtc19zdCI6eyJzdWIiOiJpQTFqcHJNaVR2LTJpd0QtN25ZVlZjTGJfR1Jrd0VLQlJraWtHTWZfYlRvIn0sInhtc190Y2R0IjoxNjkwNDYyMjc4LCJ4bXNfdGRiciI6IkVVIn0.axO_qo7fOSfdh9anwP1Hg5wvTuN8-_RDgevq30hvWZCXbKEidlKVCbq6QIZZlDss-gNl1y3ZNZhoXYgDM6hnWH2nr7kmvHTH830DNdkIkOg_i9vWKKqLINg8hUmuWZ4-MnMY--d3u0tAJd4ngWR1MwDlhhazGGodSv-GOUbLw2703LxcitN87h-rpL-5sI-0U_NTaTATskV_QqyJtVAFO2RQY32_w_-EkUMwhppTcDtAnRtZTTuRWR9C3SDZi4rWo3-Mov8v37rwzI7_UO4meowstcMiaSAGewfkNw0U__q9kmGkwLNngXuyZ0hSoBDFGBKmqB3ilYlUqn3D6n4rSQ'
```

Here is my client definition:
```yaml
clients:
    azure-token-exchange-client:
      secret: top-secret
      scope: uaa.admin,uaa.user,openid,profile,email
      authorities: uaa.admin,uaa.user,openid,profile,email
      authorized-grant-types: authorization_code,refresh_token,password,client_credentials,urn:ietf:params:oauth:grant-type:jwt-bearer
      redirect-uri: "https://login.microsoftonline.com/common/oauth2/token"
```
