### ISSUE TITLE
Timeout when using the root directory in Active Directory

### ISSUE THREAD

**Issue by gepaulwarwicker** [cloudfoundry/uaa#2664]
**SECURITY NOTICE: If you have found a security problem in the UAA, please do not file a public github issue. Instead, please send an email to security@cloudfoundry.org**

Thanks for taking the time to file an issue. You'll minimize back and forth and help us help you more effectively by answering all of the following questions as specifically and completely as you can.

### What version of UAA are you running?

Using a downstream fork of UAA which is at version 74.4.0. /info endpoint is suppressed for security reasons.
Also tried with a later version based on 76.4.0

### How are you deploying the UAA?

I am deploying the UAA

- other (please explain)
packaged for kubernetes from fork, with some modifications, as part of web application.

### What did you do?

We have a customer use case where a they can configure UAA using Active Directory at the backend and it works correctly. However, they are trying to introduce an Offshore group which necessitates them using the root of the AD to be able to specify a search criteria to cater for all possible users. (Sidenote: This is indirectly related to the request https://github.com/cloudfoundry/uaa/issues/1897 which is for the same customer and requested via a different support channel. This was closed as not planned). The LDAP directory is very large, exact size unknown.

If UAA is deployed in either the specific onshore or offshore configurations, then either the onshore or offshore users can authenticate. But if the root is specified, the request times out. Independently we have written a small standalone Java program to be run directly in the pod which reads the LDAP configuration directly from the UAA config. This can verify both onshore and offshore users using the root config which UAA cannot complete. This completes in a timely fashion and is of the order of less than 50ms.

### What did you expect to see? What goal are you trying to achieve with the UAA?

Login with no timeout

### What did you see instead?

Failed authentication

We have agreed with the customer to provide sanitised versions of their config, and if necessary log files. They are sanitised in a consistent manner.

The following is the sanitised version of their uaa.yml file

```
#####################################################################
# Spring Profile section
#####################################################################
spring_profiles: ldap,postgresql

#####################################################################
# Session timeout - since UAA version 4.8.0 (FT-613)
# The servlet.idle-timeout is in seconds, and defaults
# to 1800 seconds if not defined.
#####################################################################
servlet:
  idle-timeout: 60
  session-cookie:
    max-age: 5

#####################################################################
## Disable the `Change Email` and `Change Password` endpoints
######################################################################
disableInternalUserManagement: true

#####################################################################
# OAuth Section
#####################################################################
oauth:
  user:
    # These authorities are added as default groups to a new user.
    authorities:
      - openid
      - uaa.none
  #
  # See also: uaa/src/main/webapp/WEB-INF/spring/oauth-clients.xml and search
  #           for org.cloudfoundry.identity.uaa.client.ClientAdminBootstrap
  clients:
    admin:
      id: admin
      secret: adminsecret
      authorized-grant-types: client_credentials
      authorities: clients.read,clients.secret,clients.write,uaa.admin,clients.admin,scim.write,scim.read,scim.userids

#####################################################################
# Login Server section
#####################################################################
login:
  selfServiceLinksEnabled: false
  navEnabled: false
  branding:
    companyName: GE, Inc.
  prompt:
    username:
      text: Name
    password:
      text: Password
  appTitle: "GE Power"
  disclosureTitle: "ATTENTION"
  disclosureIntro: |
    This computer system including all related equipment,
    network devices (specifically including Internet access),
    are provided only for authorized use.
  disclosureText: |
    All computer systems may be monitored for all lawful
    purposes, including to ensure that their use is authorized,
    for management of the system, to facilitate protection against
    unauthorized access, and to verify security procedures,
    survivability and operational security.  Monitoring includes
    active attacks by authorized personnel and their entities to
    test or verify the security of the system. During monitoring,
    information may be examined, recorded, copied and used for
    authorized purposes. All information including personal
    information, placed on or sent over this system may be monitored.
    Uses of this system, authorized or unauthorized, constitutes
    consent to monitoring of this system.  Unauthorized use may
    subject you to criminal prosecution. Evidence of any such
    unauthorized use collected during monitoring may be used for
    administrative, criminal or other adverse action. Use of this
    system constitutes consent to monitoring for these purposes.
#####################################################################
# JWT (JSON Web Token) section
#
# Steps to generate the key-pair are at:
#  https://github.com/cloudfoundry/uaa/blob/master/docs/Sysadmin-Guide.rst#token-signing
#
#####################################################################
jwt:
  token:
    policy:
      # Default validity is 12-hr (43,200 seconds) for access/refresh tokens
      # accessTokenValiditySeconds: 10
      # refreshTokenValiditySeconds: 3600

#####################################################################
# PostgreSQL section
#####################################################################
database:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://uaa-postgresql-svc:5432/uaadb

#####################################################################
# LDAP Section
# Examples of two types of group mapping are presented below.
# See UAA documentation for details:
# https://github.com/cloudfoundry/uaa/blob/master/docs/UAA-LDAP.md
#####################################################################
# BEGIN ANSIBLE MANAGED BLOCK FOR UAA LDAP
ldap:
  base:
    password: <redacted>
    searchBase: 'DC=internal,DC=example,dc=org'
    searchFilter: '(&(objectcategory=person)(objectclass=user)(|(samaccountname={0})(mail={0})))'
    url: ldaps://server1.internal.example.org:636/
    userDn: smallworld@example.org
  groups:
    file: ldap/ldap-groups-map-to-scopes.xml
    groupSearchFilter: '(&(member={0})(cn=VAP-CAAS-XABBBBzzzz-ggg-nnn_PP_*))'
    maxSearchDepth: 1
    searchBase: 'OU=yyyy,OU=Prod,OU=XABBBB,OU=CaaS-BBBB,OU=Roles,OU=Groups,OU=BBBBO,DC=internal,DC=example,dc=org'
    searchSubtree: true
  profile:
    file: ldap/ldap-search-and-bind.xml
  ssl:
    skipverification: true
    tls: none
# END ANSIBLE MANAGED BLOCK FOR UAA LDAP
#####################################################################
# UAA dumps out details of request
#####################################################################
#dump_requests: true
```
Do you have any suggestions as to how we may diagnose this timeout issue further?

Regards
-paul
