### ISSUE TITLE
Prompt for temporary authentication code not requested for SSO

### ISSUE THREAD

**Issue by jcvrabo** [cloudfoundry/uaa#3363]
After the fix for #3321, single sign on  authentication stopped sending the passcode prompt, so... in version 77.28.0 the passcode prompt is broken.

version 77.27.0 returns the prompts:
```
  "prompts": {
    "username": [
      "text",
      "Email"
    ],
    "password": [
      "password",
      "Password"
    ],
    "passcode": [
      "password",
      "Temporary Authentication Code ( Get one at https://login.sys.somewhere.at/passcode )"
    ]
  },
```

and for the same configuration, version 77.28.0 returns:
```
  "prompts": {
    "username": [
      "text",
      "Email"
    ],
    "password": [
      "password",
      "Password"
    ]
  },
```

**Comment by strehle** [comment]
If you check 77.26.0 you should see

```
  "prompts": {
    "username": [
      "text",
      "Email"
    ],
    "password": [
      "password",
      "Password"
    ]
  },
```

If not then please describe your config.

The issue was on 77.27.0 and not on 77.28.0

The prompt depends on. Is there a IDP which has prompts. 
There was a change with 77.27.0 to not check all IDP (because there were perf.issues) but do some shortcut. This led to showing it by default. Then there was a problem on internal tests which did not expect them. Therefore with 77.28.0 the default was changed again.

Therefore if you need prompts for your tool, please describe your IDP config

**Comment by metskem** [comment]
I downgraded uaa to 77.26.0, then we see the following prompts:


```
  "prompts": {
    "passcode": [
      "password",
      "Temporary Authentication Code ( Get one at https://login.sys.somewhere.at/passcode )"
    ],
    "password": "[PRIVATE DATA HIDDEN]",
    "username": [
      "text",
      "Email"
    ]
  }

```

Here is some part of the cf deployment manifest for the uaa job (not sure if it contains what you are looking for though) : 

```
        oauth:
          providers:
            RaboSSO:
              addShadowUserOnLogin: false
              attributeMappings:
                email: upn
                external_groups: null
                family_name: upn
                given_name: name
                user:
                  attribute:
                    externalid: sub
                    given_name: name
                    username: upn
                user_name: upn
              discoveryUrl: https://login.microsoftonline.com/<redacted>/v2.0/.well-known/openid-configuration
              emailDomain:
              - <redacted>
              - <redacted>
              linkText: Rabo Single Signon through OIDC
              override: true
              passwordGrantEnabled: false
              relyingPartyId: ((personal_users_azure_dev_application_id))
              relyingPartySecret: ((personal_users_azure_dev_secret))
              scopes:
              - openid
              - profile
              - email
              showLinkText: true
              skipSslValidation: false
              storeCustomAttributes: true
              type: oidc1.0
            azure-oauth2-provider:
              addShadowUserOnLogin: true
              attributeMappings:
                email: upn
                external_groups: null
                family_name: appid
                given_name: appid
                user:
                  attribute:
                    externalid: upn
                    username: upn
                user_name: appid
              discoveryUrl: https://login.microsoftonline.com/<redacted>/.well-known/openid-configuration
              linkText: Rabo Single Signon through OIDC - V1
              override: true
              passwordGrantEnabled: false
              relyingPartyId: ((spn_users_azure_dev_application_id))
              relyingPartySecret: ((spn_users_azure_dev_secret))
              scopes:
              - openid
              - profile
              - email
              showLinkText: false
              skipSslValidation: false
              storeCustomAttributes: true
              type: oidc1.0
        prompt:
          password:
            text: Password
          username:
            text: Email
        saml:
          activeKeyId: key1
          entityid: http://login.sys.somewhere.at
          keys:
            key1:
              certificate: ((uaa_service_provider_key_credentials.certificate))
              key: ((uaa_service_provider_key_credentials.private_key))
              passphrase: ""
          providers:
            NotRaboSSO:
              addShadowUserOnLogin: false
              attributeMappings:
                email: upn
                external_groups: null
                family_name: family_name
                given_name: given_name
              idpMetadata: https://login.microsoftonline.com/<redacted>.onmicrosoft.com/FederationMetadata/2007-06/FederationMetadata.xml
              linkText: Rabo Single Signon through SAML
              metadataTrustCheck: false
              nameID: urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress
              showSamlLoginLink: false

```

**Comment by strehle** [comment]
Ok, thank you , the logic is, that there was a loop over all IdPs (SAML and OIDC) and the check if at least one has showSamlLoginLink or showLinkText set to true. This is what you have.

We have MANY IdPs and therefore this loop over all was removed.

After https://github.com/cloudfoundry/uaa/issues/3321 the workaround now is, that we check only for defaultIdentityProvider, this was https://github.com/cloudfoundry/uaa/pull/3323.

Therefore, can you you add / change your uaa.yml to

```
        defaultIdentityProvider: RaboSSO
	oauth:
          providers:
            RaboSSO:
              addShadowUserOnLogin: false
              attributeMappings:
                email: upn
                external_groups: null
                family_name: upn
                given_name: name

        .................

```

The setting **defaultIdentityProvider** is on same level as oauth. The entry of defaultIdentityProvider is still checked and in your case it has showLinkText=true so you should see then the extra prompt.

If this does work for you we have to think about a new solution.
