### ISSUE TITLE
default-uaa.yml is containing the list component "users:"  twice.

### ISSUE THREAD

**Issue by ratheile** [cloudfoundry/uaa#340]
While being very useful to experiment and start off, the default-uaa.yml does override its own test user example (Marissa). It took me a while to figure it out why no test user was created and i suppose that the second entry is not intended. 

```
scim:
  delete:
    deactivate: false
  userids_enabled: false # true in default profile
  user:
    override: false
  users: # example only, default is empty
    - marissa|koala|marissa@test.org|Marissa|Bloggs|uaa.user
  userids_enabled: true
  users:
  group_membership: # example only, default is empty
    - acme|acme.dev,acme.qa
    - acme.dev|marissa
```
