### ISSUE TITLE
ldap docs are still refereing to ldap.base

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry/uaa#341]
ldap.base. does not exists anymore
see
```
spring_profiles: ldap
ldap:
  profile:
    file: ldap/ldap-simple-bind.xml
  base:
    url: 'ldap://localhost:10389/'
    mailAttributeName: mail
    userDnPattern: 'cn={0},ou=Users,dc=test,dc=com;cn={0},ou=OtherUsers,dc=example,dc=com'
```

should be
```
spring_profiles: ldap
ldap:
  profile:
    file: ldap/ldap-simple-bind.xml
  url: 'ldap://localhost:10389/'
  mailAttributeName: mail
  userDnPattern: 'cn={0},ou=Users,dc=test,dc=com;cn={0},ou=OtherUsers,dc=example,dc=com'
```

and alot more of these entries
