### ISSUE TITLE
Disable lockout?

### ISSUE THREAD

**Issue by MatthiasWinzeler** [cloudfoundry/uaa#380]
We'd like to disable the lockout for internal UAA users on invalid authentication attempts.
The following configuration items seem relevant for this:

```
authentication:
  policy:
    lockoutAfterFailures: 5
    countFailuresWithinSeconds: 3600
    lockoutPeriodSeconds: 300
```

I tried various combinations: Setting all values to -1 (as the values are initalized by UAA itself) caused the UAA to lockout after 1 invalid attempt. Settting lockoutPeriodSeconds to 0 also showed no effect (user was locked out after 5 attempts).  

Is there a way to completely disable user lockout?

**Comment by plfx** [comment]
I'm unable to reproduce the behavior you're seeing. Both of the methods you tried seem to work, as does this:
```
authentication:
  policy:
    lockoutAfterFailures: 5
    countFailuresWithinSeconds: 0
    lockoutPeriodSeconds: 0
```

Could you share the relevant section of your yml?

**Comment by MatthiasWinzeler** [comment]
@plfx : I'm still being locked out with your configuration - I test against UAA 3.4.1 pushed to CF.
The relevant portions of the manifest look like this:

```
  applications:
  - name: pushed-uaa
    memory: 1024M
    instances: 2
    path: ../cloudfoundry-identity-uaa-3.4.1.war
    env:
      SPRING_PROFILES_ACTIVE: mysql
      JBP_CONFIG_SPRING_AUTO_RECONFIGURATION: '[enabled: false]'
      JBP_CONFIG_TOMCAT: '{tomcat: { version: 7.0.+ }}'
      UAA_CONFIG_YAML: |
      ...
        servlet.session-cookie.max-age: 28800
        authentication:
          policy:
            lockoutAfterFailures: 10
            countFailuresWithinSeconds: 0
            lockoutPeriodSeconds: 0
```

For testing, I do:

```
# create test user
uaac user add testuser -p testpassword --email testuser@test.local

# create client for password auth
uaac client add cf --authorized_grant_types password --authorities openid --scope openid
# with empty secret

# obtain token
curl -v -X POST 'https://path-to-pushed-uaa/oauth/token' -d 'grant_type=password&password=testpassword&scope=&username=testuser' --user cf:
```

This should give you a valid token.

Now log in with a wrong password multiple times - after 10 times, you get 
```{"error":"unauthorized","error_description":"Your account has been locked because of too many failed attempts to login."}```
