### ISSUE TITLE
Google as external identity provider fails with 400 Bad request

### ISSUE THREAD

**Issue by MatthiasWinzeler** [cloudfoundry/uaa#474]
We tried to connect Google as an external OAuth2/OIDC provider to UAA.

Relevant section in login.yml:

```
login: 
  oauth:
    providers:
      google:
        type: oidc1.0
        authUrl: https://accounts.google.com/o/oauth2/v2/auth
        tokenUrl: https://accounts.google.com/o/oauth2/v4/token
        scopes:
          - openid
        linkText: Login with google
        showLinkText: true
        addShadowUserOnLogin: true
        relyingPartyId: <redacted>
        relyingPartySecret: <redacted>
        skipSslValidation: true
        attributeMappings:
          user_name: email
```

UAA receives the a error response `400 Bad Request` from google when trying to exchange the auth code for a token. Response body:

```
{
  "error" : "invalid_request",
  "error_description" : "Parameter not allowed for this message type: response_type"
}
```

I saw that the integration tests verify integration to another UAA as an external IDP.

Just out of curiosity: Is this feature supposed to work with 3rd party OIDC/OAuth2 IDPs or is it meant to use only with another UAA?

**Comment by medvedzver** [comment]
@MatthiasWinzeler Yes, it should work with third party IDPs.

**Comment by cppforlife** [comment]
any docs how to configure it properly with google?

**Comment by medvedzver** [comment]
@cppforlife We are working on it.

**Comment by bsekar** [comment]
@cppforlife We have documented the steps to configure Google as an OIDC provider  [here](https://github.com/cloudfoundry/uaa/blob/develop/docs/google-oidc-provider.md)

**Comment by MatthiasWinzeler** [comment]
Thanks for the docs! Using the properties from the example it works fine:

```
      google:
        type: oidc1.0
        authUrl: https://accounts.google.com/o/oauth2/v2/auth
        tokenUrl: https://www.googleapis.com/oauth2/v4/token
        issuer: https://accounts.google.com
        redirectUrl: http://localhost:8080/uaa
        scopes:
          - openid
          - email
        linkText: Login with google
        showLinkText: true
        addShadowUserOnLogin: true
        relyingPartyId: <redacted>
        relyingPartySecret: <redacted>
        skipSslValidation: false
        attributeMappings:
          user_name: email
```
