### ISSUE TITLE
How to customize UAA login page?

### ISSUE THREAD

**Issue by yhjhoo** [cloudfoundry/uaa#509]
Is there a document to customize UAA login page?

**Comment by sreetummidi** [comment]
The only things customizable are listed below

```
login.branding.company_name:
    description: This name is used on the UAA Pages and in account management related communication in UAA
  login.branding.product_logo:
    description: This is a base64 encoded PNG image which will be used as the logo on all UAA pages like Login, Sign Up etc.
  login.branding.square_logo:
    description: This is a base64 encoded PNG image which will be used as the favicon for the UAA pages
  login.branding.footer_legal_text:
    description: This text appears on the footer of all UAA pages
  login.branding.footer_links:
    description: These links appear on the footer of all UAA pages. You may choose to add multiple urls for things like Support, Terms of Service etc.
    example:
      linkDisplayName: linkDisplayUrl
```
