### ISSUE TITLE
Specify maximum active tokens per user per client

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry/uaa#540]
In order to comply with https://web.nvd.nist.gov/view/800-53/Rev4/control?controlName=AC-10, we would like to be able to control the maximum number of active tokens per user per client, such that old tokens are automatically invalidated when the limit is exceeded. An example interface might look like this:

```yaml
properties:
  uaa:
    clients:
      my-client:
        max-active-tokens: 2
```

From slack:
> @jmcarp We are currently working on features along those lines. Starting with only 1 active refresh token per client/user combo

cc @rememberlenny @cnelson @mogul
