### ISSUE TITLE
Admin user / client for UAA?

### ISSUE THREAD

**Issue by MitchK** [cloudfoundry/uaa#543]
We run UAA standalone (without Cloud Foundry) and we would like to add client apps, but none of the existing users in the database have that privilege. 

So what is the UAA'ionic way for doing this? Would you create an admin user? Or an admin client?

```
uaa:
  admin:
    client_secret: some password
```

**Comment by MitchK** [comment]
Figured it out myself.

When using the "default" profile, there already is an admin client ("admin") and an admin secret ("adminsecret").

If you're not using the default profile, you can set up your client like this:
```
oauth:
  # Always override clients on startup
  client:
    override: true

  # List of OAuth clients
  clients:
    admin:
      id: admin
      secret: adminsecret
      authorized-grant-types: client_credentials
      scope: none
      authorities: uaa.admin,clients.admin,clients.read,clients.write,clients.secret
```
