### ISSUE TITLE
how to use tiles properties?

### ISSUE THREAD

**Issue by YunSangJun** [cloudfoundry/uaa#618]
If I set the tiles attribute in cf.yml, I expect the following page to appear after logging in. But it does not come out as I want. I use the cf 251 version (UAA 3.9.3)

<cf.yml>
```
  login:
     ...
     asset_base_url: xxx
     brand: xxx
     branding: 
     ...
     tiles:
       - name: Portal
          login-link: https://console.mypaas.io
     ...
```

<login page>
&lt;div class="island"&gt;
    &lt;h1&gt;Where to?&lt;/h1&gt;
    &lt;ul class="tiles"&gt;
        &lt;li id="tile-1"&gt;
            &lt;a href="https://console.mypaas.io" target="_blank" class="tile-1"&gt;
                &lt;div class="tile-icon"&gt;&lt;/div&gt;
            &lt;/a&gt;
            Portal
        &lt;/li&gt;
    &lt;/ul&gt;
&lt;/div&gt;
