### ISSUE TITLE
How to run UAA on a local machine connected to PostgreSQL

### ISSUE THREAD

**Issue by koreset** [cloudfoundry/uaa#619]
I'm hoping this is right place to ask this.
I've tried without success to setup UAA on my local machine to get it to connect to my local Postgres instance running on mac. I've followed the quick start docs provided and placed the relevant database properties in a uaa.yml file placed under the project root (I'm assuming this is where it should be placed). I've run both commands ./gradlew run and ./gradlew -Dspring.profiles.active=default,postgresql run for good measure and I dont see any tables created in my local postgres db.
My uaa.yml file contains the following
```
spring_profiles: postgresql,default
database:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql:uaa
  username: userx
  password: passwordx
  maxactive: 100
  maxidle: 10
  minidle: 3
  removeabandoned: false
  logabandoned: true
  abandonedtimeout: 300
  evictionintervalms: 15000
  caseinsensitive: false
```
May I politely ask what steps I should take to make this work for me?
Thanks.
