### ISSUE TITLE
RelayState with IDP initiated SSO not supported

### ISSUE THREAD

**Issue by MatthiasWinzeler** [cloudfoundry/uaa#633]
We configured  [Onelogin](https://onelogin.com) as a SAML IDP in UAA.
SSO works fine (both SP initiated and IDP initiated).

However, Onelogin supports sending a URL as a `RelayState` when doing IDP initiated SSO ([doc](https://support.onelogin.com/hc/en-us/articles/202673944-How-to-Use-the-OneLogin-SAML-Test-Connector)); the SP should then redirect the user to this URL after login. We would like to use this to send the user to our portal after login (currently, he sees the `Where to?` home page of the login server).

UAA currently does not seem to support it - I saw that there [are some references](https://github.com/cloudfoundry/uaa/blob/4.3.0/server/src/main/java/org/cloudfoundry/identity/uaa/authentication/SamlAssertionDecoder.java#L92) to `RelayState`, but this code is never hit when doing IDP initiated SSO.

As far as I understand, redirecting to `RelayState` after IDP initiated login is kind of a industry best practice. Could this be supported?

If I get any starting point on how to add support for this, I'll gladly try to add it myself.

Sample config to reproduce it:
UAA:

```
 nameID: urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress
 assertionConsumerIndex: 0
 metadataTrustCheck: true
 showSamlLoginLink: true
 linkText: 'Onelogin'
 attributeMappings:
   email: User.email
   family_name: User.LastName
   given_name: User.FirstName
 idpMetadata: |
   <Use metadata from OneLogin app details>
```

Onelogin:
```
Onelogin App: SAML Test Connector (IdP w/attr)
Audience: cloudfoundry-saml-login (EntityID)
Recipient: http://localhost:8080/uaa/saml/SSO/alias/cloudfoundry-saml-login
ACS Regex: .*
ACS Consumer url: http://localhost:8080/uaa/saml/SSO/alias/cloudfoundry-saml-login
Single Logout Url: http://localhost:8080/uaa/saml/SingleLogout/alias/cloudfoundry-saml-login
```
