### ISSUE TITLE
SAML group mapping

### ISSUE THREAD

**Issue by scbunn** [cloudfoundry/uaa#641]
I have UAA configured to connect to an idp (Azure) via SAML; however, I can't seem to figure out how to map groups to scopes.  When I inspect the SAML traffic I can see that Azure is sending back a groups claim that contains the GUIDs of all the groups the user belongs to.  How do I map those groups to scopes?

I have tried adding groupMappingMode: AS_SCOPES which seems to have no affect.

**Comment by fhanik** [comment]
@scbunn Can you please show us your IDP configuration so that we can help you troubleshoot it. 
An example of how we do it can be found in the integration tests
https://github.com/cloudfoundry/uaa/blob/99549eaeadd0e2a6484d4939c75e43cdda3cf0a6/uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/SamlLoginIT.java#L706

**Comment by scbunn** [comment]
```
login:
  entityBaseURL: http://server.dom:8080/uaa
  entityID: spn:<app GUID>
  saml:
    assertionConsumerIndex: 0
    signMetaData: true
    signRequest: true
    providers:
      azure:
        idpMetadata: https://login.windows.net/<domain GUID>/federationmetadata/2007-06/federationmetadata.xml
        linkText: 'Azure Active Directory'
        nameID: urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress
        metadataTrustCheck: true
        groupMappingMode: AS_SCOPES
        storeCustomAttributes: true
        emailDomain:
         - foodom.onmicrosoft.com
```

I look through the integration tests and see if I can figure it out
