### ISSUE TITLE
Could not resolve placeholder 'login.serviceProviderKey' in value "${login.serviceProviderKey}"

### ISSUE THREAD

**Issue by gu-bin** [cloudfoundry/uaa#691]
I'm trying to deploy uaa (version 45) with bosh director (version 262.3).

As described in http://bosh.io/jobs/uaa?source=github.com/cloudfoundry/uaa-release&version=45, the following properties are deprecated:

```
      login:
        saml:
          serviceProviderKey: ((uaa_service_provider_ssl.private_key))       
          serviceProviderKeyPassword: "" # TODO: Remove this when UAA defaults this value
          serviceProviderCertificate: ((uaa_service_provider_ssl.certificate))
```
So I modified them to the recommended ones:
```
      login:
        saml:
          activeKeyId: key1
          keys:
            key1:
              key: ((uaa_service_provider_ssl.private_key))
              certificate: ((uaa_service_provider_ssl.certificate))
              passphrase: ((login_saml_passphrase))
```

But the uaa job failed to start, reporting error:
```
org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'identityZoneConfigurationBootstrap' defined in ServletContext resource [/WEB-INF/spring-servlet.xml]: Could not resolve placeholder 'login.serviceProviderKey' in value "${login.serviceProviderKey}"; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'login.serviceProviderKey' in value "${login.serviceProviderKey}"
```

When I changed back to the deprecated properties, there was no problem. I wonder if the properties are really deprecated?
