### ISSUE TITLE
Apparent incompatibility with the os-conf bosh release's add_certs job

### ISSUE THREAD

**Issue by pjk25** [cloudfoundry/uaa#766]
### What version of UAA are you running?

Verson 52.4 of the uaa bosh release

### How are you deploying the UAA?

I am deploying the UAA using a bosh release I downloaded from bosh.io

### What did you do?

I'm attempting to configure Concourse auth with UAA, but concourse will not accept my cert presented by the UAA from the /token endpoint (because my ca is self-signed). I tried to use the add_certs job from the os-conf bosh release to install my custom ca, but this causes UAA to fail to start. Below are the contents of my uaa pre-start logs.

```
concourse/0:/var/vcap/sys/log/uaa# ls
pre-start.stderr.log  pre-start.stdout.log
```

```
concourse/0:/var/vcap/sys/log/uaa# cat pre-start.stderr.log 
Certificate was added to keystore
Certificate was added to keystore
Certificate was added to keystore
Certificate was added to keystore
Certificate was added to keystore
Certificate was added to keystore
Certificate was added to keystore
Certificate was added to keystore
Certificate was added to keystore
cat: /etc/ssl/certs/ca-certificates.crt: No such file or directory
```

```
concourse/0:/var/vcap/sys/log/uaa# cat pre-start.stdout.log 
uaa-pre-start - starting at Tue Feb  6 07:14:18 UTC 2018
Processing certificates for Java cacerts file
Processed certificate 1 of 173
Processed certificate 2 of 173
Processed certificate 3 of 173
Processed certificate 4 of 173
Processed certificate 5 of 173
Processed certificate 6 of 173
Processed certificate 7 of 173
Processed certificate 8 of 173
Processed certificate 9 of 173
keytool error: java.lang.Exception: Input not an X.509 certificate
```

And this is the cert installed by the os-conf release:

```
concourse/0:/var/vcap/jobs/ca_certs# cat config/certs.crt 
-----BEGIN CERTIFICATE-----
MIIEFDCCAnygAwIBAgIRAOe5yD5RXZrS8CphPzvPSVowDQYJKoZIhvcNAQELBQAw
MzEMMAoGA1UEBhMDVVNBMRYwFAYDVQQKEw1DbG91ZCBGb3VuZHJ5MQswCQYDVQQD
EwJjYTAeFw0xODAxMTgwODIzMDhaFw0xOTAxMTgwODIzMDhaMDMxDDAKBgNVBAYT
A1VTQTEWMBQGA1UEChMNQ2xvdWQgRm91bmRyeTELMAkGA1UEAxMCY2EwggGiMA0G
CSqGSIb3DQEBAQUAA4IBjwAwggGKAoIBgQC8IAtMG5faIOcsRf+leUFXsWuQ1G4k
av3vF19Jcdl/dcxrF5bnRuderuE7Y2Xh7e+dHLeQgBkEpNVNojBvQ+BX0CSo4AXv
TtPV0F3GKeLWYvYBR885Plr9+/lc5pIknplRisMeyMNLtQz59Oiqjat2Tv0wd0u/
y296zv0d3rmvYkYjPbeosxssQ7LNoR4W3IdI7Udg3C8STiNDfubGnA83jvFiCGgb
Gn13i/e1hR1We1lOuJleMHIEWlo/FJhKtOeX1IP7D8IfHTQTZ8yD/oqJcCvXNM3e
sGdXe8RQhxm9RBc7gMwh7egtlgvPBlYeQbk/chVY/4MyynCR5EkU8W6Yk3Wp4EJ/
OzRy4zIB0MlN2yhgI10MjSDwhNGMFz1IljKr2DjOrzwZ2WbiY5D13bgaS5WhQZ+f
ed2ToyN6knCSQSlVfuDQ5YGYREHcaHj6+IW2UiZBAZg91FmqITcWcaAYVb7ZMOVF
5a7zVJLI3emmKVhQf7y72s50y831OcW7TsUCAwEAAaMjMCEwDgYDVR0PAQH/BAQD
AgEGMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggGBAD6zUZc6pONw
1q1Hnh6ngMrOJ3768LeuZjHZEklMLpmnfpT24gYQB+//XUf31rR7Y+Sd777GmPkG
Th+B4aZHXgIeuJ2jjFLGrepgtqoS+ssM6ACOJO6HNWJUePJiPntZWnIxca7P/xVm
cHuFyCtYxy74df2myau/a5wzVVt4W0rMEo4UwENmnMikpr4ZVWv3pQASm9ePCz56
ARf+40rAULdS0KR2BnUnvqNnpVxTJ33TIUvbNOag2+Vic+dIeBAyfuGOrgxPbpfo
974yiihJfQfOcuRkEFI4GiZsmzh20Iz7iXi/kmdvwFglPR8s/0rDvbxO1AUL6i6J
5yUlzOzrnqU3FpuQGpM94AFXoqUXlWeMAbjJF6fJyQj03wtvWMgVOL79mq/bv35H
hfC0OD36ax24SXwJ5vp6i4rAfYLBwaeECSDLhGB1kWICcC6B4YY1Ei2Jp/Uryo4s
g17Xk0V8SpUEjIGCfOXvwAa4pudtB+6IJrrFT9jNbWbVqBPV/mrGYg==
-----END CERTIFICATE-----
```

And finally here are the properties for my uaa job in my manfest. The uaa and concourse atc are on the same vm in my deployment:

```yaml
    properties:
      uaa:
        url: "https://((lb_ip)):8443"
        sslPrivateKey: ((concourse_ssl.private_key))
        sslCertificate: ((concourse_ssl.certificate))
        jwt:
          signing_key: ((uaa_jwt_signing_key.private_key))
          verification_key: ((uaa_jwt_signing_key.public_key))
        scim:
          users:
          - name: admin
            groups: [concourse]
            password: ((admin_password))
        clients:
          concourse:
            override: true
            authorized-grant-types: authorization_code,refresh_token
            autoapprove: true
            redirect-uri: https://((lb_ip))/auth/oauth/callback
            scope: concourse
            secret: ((concourse_client_secret))
          uaa_admin:
            override: true
            authorized-grant-types: client_credentials
            scope: ""
            authorities: clients.read,clients.write,clients.secret,uaa.admin,scim.read,scim.write,password.write
            secret: ((uaa_admin_client_secret))
        login: {client_secret: ((uaa_login_client_secret))}
        zones: {internal: {hostnames: []}}
      login:
        self_service_links_enabled: false
        saml:
          serviceProviderKey: ((uaa_service_provider_ssl.private_key))
          serviceProviderKeyPassword: "" # TODO: Remove this when UAA defaults this value
          serviceProviderCertificate: ((uaa_service_provider_ssl.certificate))
      uaadb:
        address: 127.0.0.1
        port: 5432
        db_scheme: postgresql
        databases:
        - tag: uaa
          name: uaa
        roles:
        - tag: admin
          name: uaa
          password: ((uaa_db_password))
```

### What did you expect to see? What goal are you trying to achieve with the UAA?

I would expect the UAA to start as usual.

### What did you see instead?

Pre-start fails.
