### ISSUE TITLE
[cf push] java.sql.SQLException: Driver:org.hsqldb.jdbcDriver returned null for URL

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/uaa#854]
### What version of UAA are you running?

Trying to deploy master branch to PWS/CF.

### How are you deploying the UAA?

I am trying to follow the "deploy to cf" instructions in the readme. So far I'm made the following two PRs - https://github.com/cloudfoundry/uaa/pull/852, https://github.com/cloudfoundry/uaa/pull/853.

In addition, I've attempted to create + bind two different SQL services - cleardb/mysql and elephantsql/postgresql.

### What did you see instead?

In my app logs I see a variation of this error:

```
   2018-06-19T17:40:47.72+1000 [APP/PROC/WEB/0] OUT [CONTAINER] org.apache.tomcat.jdbc.pool.ConnectionPool         SEVERE  Unable to create initial connections of pool.
   2018-06-19T17:40:47.72+1000 [APP/PROC/WEB/0] OUT java.sql.SQLException: Driver:org.hsqldb.jdbcDriver@5b1cac21 returned null for URL:mysql2://xxx:yyy@us-cdbr-iron-east-04.cleardb.net:3306/zzz?reconnect=true
```

This happens for both cleardb (whose credentials provide a `jdbcUrl` property); and elephantsql (whose credentials only provide a `uri` property).

What are the recommended instructions for binding a CF SQL service to UAA?

**Comment by drnic** [comment]
I changed my manifest from suggestions in https://github.com/cloudfoundry/uaa/blob/master/docs/Sysadmin-Guide.rst#database:

```yaml
    UAA_CONFIG_YAML: |
      spring_profiles: default
      database:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgres://xxx:yyy@stampy-01.db.elephantsql.com:5432/zzz
        username: xxx
        password: yyy
        maxactive: 15
        maxidle: 5
        minidle: 1
```

But get a similar error:

```
   2018-06-19T18:49:06.57+1000 [APP/PROC/WEB/0] OUT Caused by: java.sql.SQLException: Driver:org.postgresql.Driver@1d19bec returned null for URL:postgres://xxx:yyy@stampy-01.db.elephantsql.com:5432/zzz
```

**Comment by DennisDenuto** [comment]
@drnic Thanks for creating this issue. Can you try using `jdbc:postgresql` instead of `jdbc:postgres`

Can you confirm that when you ssh into the uaa vm that you can connect to your posgresql db.

**Comment by drnic** [comment]
@DennisDenuto ahh thanks for spotting that; I should have tried harder.

For anyone else, the combo that got me past the various spring/postgresql errors when using elephantsql/tiny-turtle (max 4 connections) was:

```yaml
      spring_profiles: postgresql,default
      database:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://elmer-01.db.elephantsql.com:5432/zzz
        username: xxx
        password: yyy
        maxactive: 4
        maxidle: 3
        minidle: 1
```
