### ISSUE TITLE
Failed customizing default zone branding via UAA manifest

### ISSUE THREAD

**Issue by devshark** [cloudfoundry/uaa#944]
### What version of UAA are you running?
version 4.26.0

### How are you deploying the UAA?

I am deploying the UAA locally via docker-compose

### What did you do?
I tried customizing the default zone's branding via the UAA manifest, as per below:
```yaml
LOGIN_SECRET: <redacted>
authentication:
  policy:
    countFailuresWithinSeconds: <redacted>
    global:
      countFailuresWithinSeconds: <redacted>
      lockoutAfterFailures: <redacted>
      lockoutPeriodSeconds: <redacted>
    lockoutAfterFailures: <redacted>
    lockoutPeriodSeconds: <redacted>
authorize:
  url: <redacted>
branding:
  banner:
    backgroundColor: <redacted>
    link: <redacted>
    logo: ''
    text: <redacted>
    textColor: <redacted>
  company_name: <redacted>
  consent:
    link: <redacted>
    text: <redacted>
  footer_legal_text: <redacted>
  footer_links:
    privacyPolicy: <redacted>
    termsOfUse: <redacted>
  product_logo: ''
  square_logo: ''
database:
  driverClassName: <redacted>
  password: <redacted>
  url: <redacted>
  username: <redacted>
encryption:
  active_key_label: <redacted>
  encryption_keys: <redacted>
host: <redacted>
issuer:
  uri: <redacted>
jwt:
  token:
    signing-key: <redacted>
login:
  branding:
    banner:
      backgroundColor: <redacted>
      link: <redacted>
      logo: ''
      text: <redacted>
      textColor: <redacted>
    company_name: <redacted>
    consent:
      link: <redacted>
      text: <redacted>
    footer_legal_text: <redacted>
    footer_links:
      privacyPolicy: <redacted>
      termsOfUse: <redacted>
    product_logo: ''
    square_logo: ''
  serviceProviderCertificate: <redacted>
  serviceProviderKey: <redacted>
  serviceProviderKeyPassword: <redacted>
  url: <redacted>
password:
  policy:
    expirePasswordInMonths: <redacted>
    global:
      expirePasswordInMonths: <redacted>
      maxLength: <redacted>
      minLength: <redacted>
      requireDigit: <redacted>
      requireLowerCaseCharacter: <redacted>
      requireSpecialCharacter: <redacted>
      requireUpperCaseCharacter: <redacted>
    maxLength: <redacted>
    minLength: <redacted>
    requireDigit: <redacted>
    requireLowerCaseCharacter: <redacted>
    requireSpecialCharacter: <redacted>
    requireUpperCaseCharacter: <redacted>
smtp:
  host: <redacted>
  password: <redacted>
  port: <redacted>
  user: <redacted>
spring_profiles: <redacted>
sslCertificate: <redacted>
sslPrivateKey: <redacted>
url: <redacted>
```
Note that I duplicated the `branding` property, on different levels, on-purpose for testing.

### What did you expect to see? What goal are you trying to achieve with the UAA?
I expect my default zone's pages to be as I customized. The branding text, footer text, links, etc should be as what I set in the UAA manifest.

### What did you see instead?
It displayed the default "CloudFoundry" branding.
