### ISSUE TITLE
Does UAA works with MySQL 8?

### ISSUE THREAD

**Issue by RodrigoPetter** [cloudfoundry/uaa#957]
### What version of UAA are you running?

4.28.0

### How are you deploying the UAA?

I am deploying the UAA locally only using gradlew

### What did you do?

1.  Started a MySQL 8 docker container
2.  Used the following config in uaa.yml:
```
database:
  driverClassName: org.mariadb.jdbc.Driver #com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/uaa_hom
  username: migration
  password: m1gr@t10n
```
3.  Started UAA with `./gradlew run`

### What did you expect to see? What goal are you trying to achieve with the UAA?

Expected a successful database connection.

### What did you see instead?

I received an `Access denied for user 'migration'@'127.0.0.1' (using password: YES)`;

**Everything works if I use the same setup, only changing the mysql version to 5.**
